version: '3'
services:
  app:
    build: .
    command: sh -c "yarn start"
    volumes:
      - .:/myapp
    ports:
      - 8080:3000
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true

